/*
 *  WARNING, DO NOT EDIT: THIS IS AUTOGENERATED BY GRUNT!
 */
define("collections", [
    'underscore',
    "collections/aggregations"
], function(_) {
    "use strict";
    var key, collections = {};

    _.each(arguments, function(value, key, list) {
        if(value !== _ && !value && value.prototype.name) {
            throw new Error('All collections have to have a name!');
        }
        _ !== value ? collections[value.prototype.name] = value : _.isEmpty();
    });

    return {
        get: function(name) {
            if(name in collections) {
                return collections[name];
            }
        }
    };
});
