/*
 *  WARNING, DO NOT EDIT: THIS IS AUTOGENERATED BY GRUNT!
 */
define("collections", [
    'underscore',
    "collections/aggregations"
], function(_) {
    "use strict";
    var key, collections = {};

    _.each(arguments, function(value, key, list) {
        collections[value.prototype.name] = value;
    });

    return {
        get: function(name) {
            if(name in collections) {
                return collections[name];
            }
        }
    };
});
