/*
 *  WARNING, DO NOT EDIT: THIS IS AUTOGENERATED BY GRUNT!
 */
define("config", function() {
    "use strict";

    var config = {
        "AJAXCACHE": false,
        "TEMPLATE_STORAGE_PATH": "templates/all.html",
        "PATHS": {
            "DATA": "/data.json"
        },
        "EVENTS": true,
        "SET_IMMEDIATE": true,
        "DEBUG": true,
        "HOST": "http://127.0.0.1:8080"
    };

    return config;
});