#!/bin/bash

cd application

CMDS="npm"

for i in $CMDS
do
    # command -v will return >0 when the $i is not found
    command -v $i >/dev/null && continue || { echo "[$i] : Command not found."; exit 1; }
done

SYSWIDE_NPM_DEPS="jamjs grunt"
LOCAL_NPM_DEPS="wrench node-static http-proxy"

echo "Installing system wide dependencies [$SYSWIDE_NPM_DEPS], we need to sudo to do that."
for DEPENDENCY in $SYSWIDE_NPM_DEPS
do
    sudo npm -g install $DEPENDENCY
done

for DEPENDENCY in $LOCAL_NPM_DEPS
do
    npm install $DEPENDENCY
done

# Install project dependencies
jam install backbone jquery underscore underscore.string less bootstrap transparency keymaster domReady

cd ..

if [ ! -d ~/.grunt ]
then
    mkdir ~/.grunt
fi

rm ~/.grunt/tasks
ln -s `pwd`/tasks ~/.grunt/tasks

#ln -s ~/node_modules node_modules
