/*
*  WARNING, DO NOT EDIT: THIS IS AUTOGENERATED BY GRUNT!
*/
define("specs", [
    "test/features/ajaxError",
    "test/features/application",
    "test/features/baseFeature",
    "test/features/featureContainer",
    "test/features/viewportController",
    "test/features/VisibleFeature",
    "test/features/windowEventDispatcher",
    "test/features/accordion/accordion",
    "test/features/column/column",
    "test/features/keymaster/KeyMaster",
    "test/features/navigation/navigation",
    "test/features/router/router",
    "test/features/router/notFound/notFound",
    "test/features/sample/sample",
    "test/features/section/section",
    "test/features/utils/loading/loading",
    "test/features/utils/toaster/toaster",
    "test/tools/eventmachine",
    "test/tools/templatestorage",
    "test/tools/urls",
    "test/collections/aggregations"
], function() {});
